export const API_ENDPOINTS = {
  ADMIN: {
    USERS: '/api/admin/users',
    USERS_BLOCK: (id) => `/api/admin/users/${id}/block`,
    PRODUCTS: '/api/admin/products',
    PRODUCT: (id) => `/api/admin/products/${id}`,
    CATEGORIES: '/api/admin/categories',
    CATEGORY: (id) => `/api/admin/categories/${id}`,
    CATEGORY_OFFER: '/api/admin/category/offer',
    CATEGORY_OFFER_REMOVE: '/api/admin/category/offer/remove',
    PRODUCT_OFFER: (id) => `/api/admin/products/${id}/offer`,
    COUPONS: '/api/admin/coupons',
    COUPON: (id) => `/api/admin/coupons/${id}`,
    ORDERS: '/api/admin/orders',
    ORDER: (id) => `/api/admin/orders/${id}`,
    ORDER_ITEM_STATUS: (orderId, productId) => `/api/admin/orders/${orderId}/items/${productId}`,
    APPROVE_RETURN: (orderId, productId) => `/api/admin/orders/${orderId}/items/${productId}/approve-return`,
    REJECT_RETURN: (orderId, productId) => `/api/admin/orders/${orderId}/items/${productId}/reject-return`,
    SALES_REPORT: '/api/admin/sales-report',
    DASHBOARD: '/api/admin/dashboard',
  },
  AUTH: {
    REGISTER: '/api/auth/register',
    LOGIN: '/api/auth/login',
    LOGOUT: '/api/auth/logout',
    VERIFY: '/api/auth/verify',
    RESEND_OTP: '/api/auth/resend-otp',
    FORGET_PASSWORD: '/api/auth/forget-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    SET: '/api/auth/set',
    GOOGLE: '/api/auth/google',
    GOOGLE_CALLBACK: '/api/auth/google/callback',
    REFRESH_TOKEN: '/api/auth/refresh-token',
  },
  COMMON: {
    UPLOAD: '/api/upload',
    FEATURED: '/api/featured',
    PRODUCTS: '/api/products',
    PRODUCT: (id) => `/api/products/${id}`,
    CATEGORIES: '/api/categories',
    CHECK_QUANTITY: '/api/check-quantity',
  },
  USER: {
    CART: '/api/user/cart',
    CART_SYNC: '/api/user/cart/sync',
    CART_ITEM: (itemId) => `/api/user/cart/${itemId}`,
    CART_CLEAR: '/api/user/cart/clear',
    BASE: '/api/user',
    CHANGE_PASSWORD: '/api/user/change-password',
    ADDRESSES: '/api/user/addresses',
    ADDRESS: (id) => `/api/user/addresses/${id}`,
    ADDRESS_SET_DEFAULT: (id) => `/api/user/addresses/${id}/set-default`,
    ORDER: '/api/user/order',
    ORDER_BY_ID: (id) => `/api/user/order/${id}`,
    ORDER_CANCEL: (id) => `/api/user/order/${id}/cancel`,
    ORDER_RETURN: (id) => `/api/user/order/${id}/return`,
    COUPONS: '/api/user/coupons',
    APPLY_COUPON: '/api/user/apply-coupon',
    CHECK_COUPON: '/api/user/check-coupon',
    CREATE_RAZORPAY_ORDER: '/api/user/create-razorpay-order',
    VERIFY_PAYMENT: '/api/user/verify-payment',
    PAYMENT_FAILURE: '/api/user/payment-failure',
    WISHLIST: '/api/user/wishlist',
    WISHLIST_ITEM: (productId, variantId) => `/api/user/wishlist/${productId}/${variantId}`,
    WALLET: '/api/user/wallet',
    WALLET_PAYMENT: '/api/user/wallet-payment',
    WALLET_ADD_MONEY: '/api/user/wallet/add-money',
    WALLET_TRANSACTIONS: '/api/user/wallet/transactions',
    APPLY_REFERRAL: '/api/user/apply-referral',
    REFERRAL_CODE: '/api/user/referral-code',
    REFERRED_COUNT: '/api/user/referred-count',
  },
};
