const ROUTES = Object.freeze({
  ADMIN: {
    USERS: '/users',
    USERS_BY_ID_BLOCK: '/users/:id/block',
    PRODUCTS: '/products',
    PRODUCTS_BY_ID: '/products/:id',
    CATEGORIES: '/categories',
    CATEGORIES_BY_ID: '/categories/:id',
    CATEGORY_OFFER: '/category/offer',
    CATEGORY_OFFER_REMOVE: '/category/offer/remove',
    PRODUCTS_BY_ID_OFFER: '/products/:id/offer',
    COUPONS: '/coupons',
    COUPONS_BY_ID: '/coupons/:id',
    ORDERS: '/orders',
    ORDERS_BY_ID: '/orders/:id',
    ORDERS_BY_ORDERID_ITEMS_BY_PRODUCTID: '/orders/:orderId/items/:productId',
    ORDERS_BY_ORDERID_ITEMS_BY_PRODUCTID_APPROVE_RETURN: '/orders/:orderId/items/:productId/approve-return',
    ORDERS_BY_ORDERID_ITEMS_BY_PRODUCTID_REJECT_RETURN: '/orders/:orderId/items/:productId/reject-return',
    SALES_REPORT: '/sales-report',
    DASHBOARD: '/dashboard',
  },
  AUTH: {
    REGISTER: '/register',
    LOGIN: '/login',
    LOGOUT: '/logout',
    VERIFY: '/verify',
    RESEND_OTP: '/resend-otp',
    FORGET_PASSWORD: '/forget-password',
    RESET_PASSWORD: '/reset-password',
    SET: '/set',
    GOOGLE: '/google',
    GOOGLE_CALLBACK: '/google/callback',
    REFRESH_TOKEN: '/refresh-token',
  },
  COMMON: {
    UPLOAD: '/upload',
    FEATURED: '/featured',
    PRODUCTS: '/products',
    PRODUCTS_BY_ID: '/products/:id',
    CATEGORIES: '/categories',
    CHECK_QUANTITY: '/check-quantity',
  },
  USER: {
    CART: '/cart',
    CART_SYNC: '/cart/sync',
    CART_BY_ITEMID: '/cart/:itemId',
    CART_CLEAR: '/cart/clear',
    BASE: '/',
    CHANGE_PASSWORD: '/change-password',
    ADDRESSES: '/addresses',
    ADDRESSES_BY_ID: '/addresses/:id',
    ADDRESSES_BY_ID_SET_DEFAULT: '/addresses/:id/set-default',
    ORDER: '/order',
    ORDER_BY_ID: '/order/:id',
    ORDER_BY_ID_CANCEL: '/order/:id/cancel',
    ORDER_BY_ID_RETURN: '/order/:id/return',
    COUPONS: '/coupons',
    APPLY_COUPON: '/apply-coupon',
    CHECK_COUPON: '/check-coupon',
    CREATE_RAZORPAY_ORDER: '/create-razorpay-order',
    VERIFY_PAYMENT: '/verify-payment',
    PAYMENT_FAILURE: '/payment-failure',
    WISHLIST: '/wishlist',
    WISHLIST_BY_PRODUCTID_BY_VARIANTID: '/wishlist/:productId/:variantId',
    WALLET: '/wallet',
    WALLET_PAYMENT: '/wallet-payment',
    WALLET_ADD_MONEY: '/wallet/add-money',
    WALLET_TRANSACTIONS: '/wallet/transactions',
    APPLY_REFERRAL: '/apply-referral',
    REFERRAL_CODE: '/referral-code',
    REFERRED_COUNT: '/referred-count',
  },
});

module.exports = ROUTES;
